// Generated by Haxe 4.1.3
package apparentridges._ApparentRidges;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Face_Impl_
{
	public static int[] _new(int a, int b, int c)
	{
		int[] this1 = new int[3];
		int[] this2 = ((int[]) (this1) );
		((int[]) (this2) )[0] = a;
		((int[]) (this2) )[1] = b;
		((int[]) (this2) )[2] = c;
		return ((int[]) (this2) );
	}
	
	
	public static int get(int[] this1, int i)
	{
		return ((int[]) (this1) )[i];
	}
	
	
	public static int set(int[] this1, int i, int v)
	{
		((int[]) (this1) )[i] = v;
		return v;
	}
	
	
	public static int indexOf(int[] this1, int v)
	{
		if (( ((int[]) (this1) )[0] == v )) 
		{
			return 0;
		}
		
		if (( ((int[]) (this1) )[1] == v )) 
		{
			return 1;
		}
		
		if (( ((int[]) (this1) )[2] == v )) 
		{
			return 2;
		}
		
		return -1;
	}
	
	
}


