// Generated by Haxe 4.1.3
package apparentridges;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Render_buildPolylines_2043__Fun extends haxe.lang.Function
{
	public Render_buildPolylines_2043__Fun()
	{
		super(1, 0);
	}
	
	
	public static apparentridges.Render_buildPolylines_2043__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		apparentridges.Line a = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((apparentridges.Line) (((java.lang.Object) (__fn_float1) )) )) : (((apparentridges.Line) (__fn_dyn1) )) );
		haxe.root.Array<double[]> this1 = new haxe.root.Array<double[]>(new double[][]{});
		haxe.root.Array<double[]> p = ((haxe.root.Array<double[]>) (this1) );
		{
			double _x = a.x1;
			double _y = a.y1;
			double _z = a.opacity1;
			double[] this2 = new double[3];
			double[] this3 = ((double[]) (this2) );
			((double[]) (this3) )[0] = _x;
			((double[]) (this3) )[1] = _y;
			((double[]) (this3) )[2] = _z;
			((haxe.root.Array<double[]>) (p) ).push(((double[]) (this3) ));
		}
		
		{
			double _x1 = a.x2;
			double _y1 = a.y2;
			double _z1 = a.opacity2;
			double[] this4 = new double[3];
			double[] this5 = ((double[]) (this4) );
			((double[]) (this5) )[0] = _x1;
			((double[]) (this5) )[1] = _y1;
			((double[]) (this5) )[2] = _z1;
			((haxe.root.Array<double[]>) (p) ).push(((double[]) (this5) ));
		}
		
		return p;
	}
	
	
}


