// Generated by Haxe 4.1.3
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Std
{
	public Std()
	{
	}
	
	
	public static boolean isOfType(java.lang.Object v, java.lang.Object t)
	{
		if (( v == null )) 
		{
			return false;
		}
		
		if (( t == null )) 
		{
			return false;
		}
		
		java.lang.Class clt = ((java.lang.Class) (t) );
		if (( ((java.lang.Object) (clt) ) == ((java.lang.Object) (null) ) )) 
		{
			return false;
		}
		
		java.lang.String name = clt.getName();
		{
			java.lang.String __temp_svar1 = (name);
			int __temp_hash3 = __temp_svar1.hashCode();
			if (( __temp_svar1 != null )) 
			{
				switch (__temp_hash3)
				{
					case 344809556:
					case 64711720:
					{
						if (( (( ( __temp_hash3 == 344809556 ) && __temp_svar1.equals("java.lang.Boolean") )) || __temp_svar1.equals("boolean") )) 
						{
							return v instanceof java.lang.Boolean;
						}
						
						break;
					}
					
					
					case 1063877011:
					{
						if (__temp_svar1.equals("java.lang.Object")) 
						{
							return true;
						}
						
						break;
					}
					
					
					case 761287205:
					case -1325958191:
					{
						if (( (( ( __temp_hash3 == 761287205 ) && __temp_svar1.equals("java.lang.Double") )) || __temp_svar1.equals("double") )) 
						{
							return haxe.lang.Runtime.isDouble(v);
						}
						
						break;
					}
					
					
					case -2056817302:
					case 104431:
					{
						if (( (( ( __temp_hash3 == -2056817302 ) && __temp_svar1.equals("java.lang.Integer") )) || __temp_svar1.equals("int") )) 
						{
							return haxe.lang.Runtime.isInt(v);
						}
						
						break;
					}
					
					
				}
				
			}
			
		}
		
		java.lang.Class clv = v.getClass();
		return clt.isAssignableFrom(((java.lang.Class) (clv) ));
	}
	
	
	public static java.lang.String string(java.lang.Object s)
	{
		return ( haxe.lang.Runtime.toString(s) + "" );
	}
	
	
	public static int _int(double x)
	{
		return ((int) (x) );
	}
	
	
	public static java.lang.Object parseInt(java.lang.String x)
	{
		try 
		{
			if (( x == null )) 
			{
				return null;
			}
			
			int base = 10;
			int len = x.length();
			int foundCount = 0;
			int sign = 0;
			int firstDigitIndex = 0;
			int lastDigitIndex = -1;
			int previous = 0;
			{
				int _g = 0;
				int _g1 = len;
				label1:
				while (( _g < _g1 ))
				{
					int i = _g++;
					int c = ( (( i < x.length() )) ? (((int) (((java.lang.String) (((java.lang.Object) (x) )) ).charAt(i)) )) : (-1) );
					if (( ( ( c > 8 ) && ( c < 14 ) ) || ( c == 32 ) )) 
					{
						if (( foundCount > 0 )) 
						{
							return null;
						}
						
						continue;
					}
					else
					{
						switch (c)
						{
							case 43:
							{
								if (( foundCount == 0 )) 
								{
									sign = 1;
								}
								else
								{
									if ( ! ((( ( 48 <= c ) && ( c <= 57 ) ))) ) 
									{
										if ( ! ((( ( base == 16 ) && (( ( ( 97 <= c ) && ( c <= 122 ) ) || ( ( 65 <= c ) && ( c <= 90 ) ) )) ))) ) 
										{
											break label1;
										}
										
									}
									
								}
								
								break;
							}
							
							
							case 45:
							{
								if (( foundCount == 0 )) 
								{
									sign = -1;
								}
								else
								{
									if ( ! ((( ( 48 <= c ) && ( c <= 57 ) ))) ) 
									{
										if ( ! ((( ( base == 16 ) && (( ( ( 97 <= c ) && ( c <= 122 ) ) || ( ( 65 <= c ) && ( c <= 90 ) ) )) ))) ) 
										{
											break label1;
										}
										
									}
									
								}
								
								break;
							}
							
							
							case 48:
							{
								if ( ! ((( ( foundCount == 0 ) || ( ( foundCount == 1 ) && ( sign != 0 ) ) ))) ) 
								{
									if ( ! ((( ( 48 <= c ) && ( c <= 57 ) ))) ) 
									{
										if ( ! ((( ( base == 16 ) && (( ( ( 97 <= c ) && ( c <= 122 ) ) || ( ( 65 <= c ) && ( c <= 90 ) ) )) ))) ) 
										{
											break label1;
										}
										
									}
									
								}
								
								break;
							}
							
							
							case 88:
							case 120:
							{
								if (( ( previous == 48 ) && (( ( ( foundCount == 1 ) && ( sign == 0 ) ) || ( ( foundCount == 2 ) && ( sign != 0 ) ) )) )) 
								{
									base = 16;
								}
								else
								{
									if ( ! ((( ( 48 <= c ) && ( c <= 57 ) ))) ) 
									{
										if ( ! ((( ( base == 16 ) && (( ( ( 97 <= c ) && ( c <= 122 ) ) || ( ( 65 <= c ) && ( c <= 90 ) ) )) ))) ) 
										{
											break label1;
										}
										
									}
									
								}
								
								break;
							}
							
							
							default:
							{
								if ( ! ((( ( 48 <= c ) && ( c <= 57 ) ))) ) 
								{
									if ( ! ((( ( base == 16 ) && (( ( ( 97 <= c ) && ( c <= 122 ) ) || ( ( 65 <= c ) && ( c <= 90 ) ) )) ))) ) 
									{
										break label1;
									}
									
								}
								
								break;
							}
							
						}
						
					}
					
					if (( ( ( foundCount == 0 ) && ( sign == 0 ) ) || ( ( foundCount == 1 ) && ( sign != 0 ) ) )) 
					{
						firstDigitIndex = i;
					}
					
					 ++ foundCount;
					lastDigitIndex = i;
					previous = c;
				}
				;
			}
			
			if (( firstDigitIndex <= lastDigitIndex )) 
			{
				java.lang.String digits = haxe.lang.StringExt.substring(x, ( firstDigitIndex + (( (( base == 16 )) ? (2) : (0) )) ), ( lastDigitIndex + 1 ));
				try 
				{
					return ( (( (( sign == -1 )) ? (-1) : (1) )) * java.lang.Integer.parseInt(haxe.lang.Runtime.toString(digits), ((int) (base) )) );
				}
				catch (java.lang.NumberFormatException e)
				{
					return null;
				}
				
				
			}
			
			return null;
		}
		catch (java.lang.Throwable typedException)
		{
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(typedException)) );
		}
		
		
	}
	
	
	public static double parseFloat(java.lang.String x)
	{
		if (( x == null )) 
		{
			return java.lang.Double.NaN;
		}
		
		x = haxe.root.StringTools.ltrim(x);
		boolean found = false;
		boolean hasDot = false;
		boolean hasSign = false;
		boolean hasE = false;
		boolean hasESign = false;
		boolean hasEData = false;
		int i = -1;
		label1:
		while ((  ++ i < x.length() ))
		{
			int chr = ((int) (x.charAt(i)) );
			if (( ( chr >= 48 ) && ( chr <= 57 ) )) 
			{
				if (hasE) 
				{
					hasEData = true;
				}
				
				found = true;
			}
			else
			{
				switch (chr)
				{
					case 43:
					case 45:
					{
						if ((  ! (found)  &&  ! (hasSign)  )) 
						{
							hasSign = true;
						}
						else
						{
							if (( ( ( found &&  ! (hasESign)  ) && hasE ) &&  ! (hasEData)  )) 
							{
								hasESign = true;
							}
							else
							{
								break label1;
							}
							
						}
						
						break;
					}
					
					
					case 46:
					{
						if ( ! (hasDot) ) 
						{
							hasDot = true;
						}
						else
						{
							break label1;
						}
						
						break;
					}
					
					
					case 69:
					case 101:
					{
						if ( ! (hasE) ) 
						{
							hasE = true;
						}
						else
						{
							break label1;
						}
						
						break;
					}
					
					
					default:
					{
						break label1;
					}
					
				}
				
			}
			
		}
		;
		if (( hasE &&  ! (hasEData)  )) 
		{
			 -- i;
			if (hasESign) 
			{
				 -- i;
			}
			
		}
		
		if (( i != x.length() )) 
		{
			x = haxe.lang.StringExt.substr(x, 0, i);
		}
		
		try 
		{
			return java.lang.Double.parseDouble(haxe.lang.Runtime.toString(x));
		}
		catch (java.lang.Throwable _g)
		{
			return java.lang.Double.NaN;
		}
		
		
	}
	
	
}


