// Generated by Haxe 4.1.3
package sys.io;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FileInput extends haxe.io.Input
{
	public FileInput(haxe.lang.EmptyObject empty)
	{
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public FileInput(java.io.RandomAccessFile f)
	{
		sys.io.FileInput.__hx_ctor_sys_io_FileInput(this, f);
	}
	
	
	protected static void __hx_ctor_sys_io_FileInput(sys.io.FileInput __hx_this, java.io.RandomAccessFile f)
	{
		__hx_this.f = f;
		__hx_this._eof = false;
	}
	
	
	public java.io.RandomAccessFile f;
	
	public boolean _eof;
	
	public void close()
	{
		try 
		{
			this.f.close();
		}
		catch (java.lang.Throwable _g)
		{
			java.lang.Object e = ((java.lang.Object) (haxe.Exception.caught(_g).unwrap()) );
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(e)) );
		}
		
		
	}
	
	
	@Override public int readByte()
	{
		try 
		{
			return this.f.readUnsignedByte();
		}
		catch (java.io.EOFException e)
		{
			this._eof = true;
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new haxe.io.Eof())) );
		}
		
		catch (java.io.IOException e1)
		{
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(haxe.io.Error.Custom(e1))) );
		}
		
		
	}
	
	
	@Override public int readBytes(haxe.io.Bytes s, int pos, int len)
	{
		int ret = 0;
		try 
		{
			ret = this.f.read(((byte[]) (s.b) ), ((int) (pos) ), ((int) (len) ));
		}
		catch (java.io.EOFException e)
		{
			this._eof = true;
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new haxe.io.Eof())) );
		}
		
		catch (java.io.IOException e1)
		{
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(haxe.io.Error.Custom(e1))) );
		}
		
		
		if (( ret == -1 )) 
		{
			this._eof = true;
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new haxe.io.Eof())) );
		}
		
		return ret;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			if (( field != null )) 
			{
				switch (field.hashCode())
				{
					case 2930749:
					{
						if (field.equals("_eof")) 
						{
							__temp_executeDef1 = false;
							this._eof = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
							return value;
						}
						
						break;
					}
					
					
					case 102:
					{
						if (field.equals("f")) 
						{
							__temp_executeDef1 = false;
							this.f = ((java.io.RandomAccessFile) (value) );
							return value;
						}
						
						break;
					}
					
					
				}
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			if (( field != null )) 
			{
				switch (field.hashCode())
				{
					case -1140063115:
					{
						if (field.equals("readBytes")) 
						{
							__temp_executeDef1 = false;
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readBytes")) );
						}
						
						break;
					}
					
					
					case 102:
					{
						if (field.equals("f")) 
						{
							__temp_executeDef1 = false;
							return this.f;
						}
						
						break;
					}
					
					
					case -868060226:
					{
						if (field.equals("readByte")) 
						{
							__temp_executeDef1 = false;
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readByte")) );
						}
						
						break;
					}
					
					
					case 2930749:
					{
						if (field.equals("_eof")) 
						{
							__temp_executeDef1 = false;
							return this._eof;
						}
						
						break;
					}
					
					
					case 94756344:
					{
						if (field.equals("close")) 
						{
							__temp_executeDef1 = false;
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "close")) );
						}
						
						break;
					}
					
					
				}
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		{
			int __temp_hash2 = field.hashCode();
			boolean __temp_executeDef1 = true;
			if (( field != null )) 
			{
				switch (__temp_hash2)
				{
					case -1140063115:
					case -868060226:
					{
						if (( (( ( __temp_hash2 == -1140063115 ) && field.equals("readBytes") )) || field.equals("readByte") )) 
						{
							__temp_executeDef1 = false;
							return haxe.lang.Runtime.slowCallField(this, field, dynargs);
						}
						
						break;
					}
					
					
					case 94756344:
					{
						if (field.equals("close")) 
						{
							__temp_executeDef1 = false;
							this.close();
						}
						
						break;
					}
					
					
				}
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("_eof");
		baseArr.push("f");
		super.__hx_getFields(baseArr);
	}
	
	
}


