// Generated by Haxe 4.1.3
#include <hxcpp.h>

#ifndef INCLUDED_95f339a1d026d52c
#define INCLUDED_95f339a1d026d52c
#include "hxMath.h"
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_apparentridges__ApparentRidges_Polyline_Impl_
#include <apparentridges/_ApparentRidges/Polyline_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1400__new,"apparentridges._ApparentRidges.Polyline_Impl_","_new",0x282ee214,"apparentridges._ApparentRidges.Polyline_Impl_._new","apparentridges/ApparentRidges.hx",1400,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1404_get_length,"apparentridges._ApparentRidges.Polyline_Impl_","get_length",0x5c01d9a2,"apparentridges._ApparentRidges.Polyline_Impl_.get_length","apparentridges/ApparentRidges.hx",1404,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1407_set_length,"apparentridges._ApparentRidges.Polyline_Impl_","set_length",0x5f7f7816,"apparentridges._ApparentRidges.Polyline_Impl_.set_length","apparentridges/ApparentRidges.hx",1407,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1410_startY,"apparentridges._ApparentRidges.Polyline_Impl_","startY",0x2c1d012a,"apparentridges._ApparentRidges.Polyline_Impl_.startY","apparentridges/ApparentRidges.hx",1410,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1413_endY,"apparentridges._ApparentRidges.Polyline_Impl_","endY",0x2c2628d1,"apparentridges._ApparentRidges.Polyline_Impl_.endY","apparentridges/ApparentRidges.hx",1413,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1416_startX,"apparentridges._ApparentRidges.Polyline_Impl_","startX",0x2c1d0129,"apparentridges._ApparentRidges.Polyline_Impl_.startX","apparentridges/ApparentRidges.hx",1416,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1419_endX,"apparentridges._ApparentRidges.Polyline_Impl_","endX",0x2c2628d0,"apparentridges._ApparentRidges.Polyline_Impl_.endX","apparentridges/ApparentRidges.hx",1419,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1423_get,"apparentridges._ApparentRidges.Polyline_Impl_","get",0x77980b43,"apparentridges._ApparentRidges.Polyline_Impl_.get","apparentridges/ApparentRidges.hx",1423,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1426_set,"apparentridges._ApparentRidges.Polyline_Impl_","set",0x77a1264f,"apparentridges._ApparentRidges.Polyline_Impl_.set","apparentridges/ApparentRidges.hx",1426,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1430_push,"apparentridges._ApparentRidges.Polyline_Impl_","push",0x3370de8d,"apparentridges._ApparentRidges.Polyline_Impl_.push","apparentridges/ApparentRidges.hx",1430,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_74c1d44c10418608_1435_unshift,"apparentridges._ApparentRidges.Polyline_Impl_","unshift",0xb0dcc8b6,"apparentridges._ApparentRidges.Polyline_Impl_.unshift","apparentridges/ApparentRidges.hx",1435,0xfeacc84f)
namespace apparentridges{
namespace _ApparentRidges{

void Polyline_Impl__obj::__construct() { }

Dynamic Polyline_Impl__obj::__CreateEmpty() { return new Polyline_Impl__obj; }

void *Polyline_Impl__obj::_hx_vtable = 0;

Dynamic Polyline_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Polyline_Impl__obj > _hx_result = new Polyline_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Polyline_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x72dfe71b;
}

::Array< ::Dynamic> Polyline_Impl__obj::_new(){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1400__new)
HXDLIN(1400)		::Array< ::Dynamic> this1 = ::Array_obj< ::Dynamic>::__new(0);
HXDLIN(1400)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Polyline_Impl__obj,_new,return )

int Polyline_Impl__obj::get_length(::Array< ::Dynamic> this1){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1404_get_length)
HXDLIN(1404)		return this1->length;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Polyline_Impl__obj,get_length,return )

int Polyline_Impl__obj::set_length(::Array< ::Dynamic> this1,int v){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1407_set_length)
HXDLIN(1407)		return this1->length;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Polyline_Impl__obj,set_length,return )

int Polyline_Impl__obj::startY(::Array< ::Dynamic> this1){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1410_startY)
HXDLIN(1410)		return ::Std_obj::_hx_int(( (Float)(::Math_obj::round(( (Float)(_hx_array_unsafe_get(this1->__get(0).StaticCast< ::Array< Float > >(),1)) ))) ));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Polyline_Impl__obj,startY,return )

int Polyline_Impl__obj::endY(::Array< ::Dynamic> this1){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1413_endY)
HXDLIN(1413)		return ::Std_obj::_hx_int(( (Float)(::Math_obj::round(( (Float)(_hx_array_unsafe_get(this1->__get((this1->length - 1)).StaticCast< ::Array< Float > >(),1)) ))) ));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Polyline_Impl__obj,endY,return )

Float Polyline_Impl__obj::startX(::Array< ::Dynamic> this1){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1416_startX)
HXDLIN(1416)		return ( (Float)(_hx_array_unsafe_get(this1->__get(0).StaticCast< ::Array< Float > >(),0)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Polyline_Impl__obj,startX,return )

Float Polyline_Impl__obj::endX(::Array< ::Dynamic> this1){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1419_endX)
HXDLIN(1419)		return ( (Float)(_hx_array_unsafe_get(this1->__get((this1->length - 1)).StaticCast< ::Array< Float > >(),0)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Polyline_Impl__obj,endX,return )

::Array< Float > Polyline_Impl__obj::get(::Array< ::Dynamic> this1,int i){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1423_get)
HXDLIN(1423)		return this1->__get(i).StaticCast< ::Array< Float > >();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Polyline_Impl__obj,get,return )

::Array< Float > Polyline_Impl__obj::set(::Array< ::Dynamic> this1,int i,::Array< Float > v){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1426_set)
HXLINE(1427)		this1[i] = v;
HXLINE(1428)		return v;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Polyline_Impl__obj,set,return )

int Polyline_Impl__obj::push(::Array< ::Dynamic> this1,::Array< Float > v){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1430_push)
HXLINE(1431)		this1->push(v);
HXLINE(1432)		return this1->length;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Polyline_Impl__obj,push,return )

void Polyline_Impl__obj::unshift(::Array< ::Dynamic> this1,::Array< Float > v){
            	HX_STACKFRAME(&_hx_pos_74c1d44c10418608_1435_unshift)
HXDLIN(1435)		this1->unshift(v);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Polyline_Impl__obj,unshift,(void))


Polyline_Impl__obj::Polyline_Impl__obj()
{
}

bool Polyline_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set") ) { outValue = set_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"endY") ) { outValue = endY_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"endX") ) { outValue = endX_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"push") ) { outValue = push_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"startY") ) { outValue = startY_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"startX") ) { outValue = startX_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"unshift") ) { outValue = unshift_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"get_length") ) { outValue = get_length_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_length") ) { outValue = set_length_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Polyline_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Polyline_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class Polyline_Impl__obj::__mClass;

static ::String Polyline_Impl__obj_sStaticFields[] = {
	HX_("_new",61,15,1f,3f),
	HX_("get_length",af,04,8f,8f),
	HX_("set_length",23,a3,0c,93),
	HX_("startY",b7,61,fa,05),
	HX_("endY",1e,5c,16,43),
	HX_("startX",b6,61,fa,05),
	HX_("endX",1d,5c,16,43),
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("push",da,11,61,4a),
	HX_("unshift",89,e3,b3,78),
	::String(null())
};

void Polyline_Impl__obj::__register()
{
	Polyline_Impl__obj _hx_dummy;
	Polyline_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("apparentridges._ApparentRidges.Polyline_Impl_",9b,d0,9d,ae);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Polyline_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Polyline_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Polyline_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Polyline_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Polyline_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace apparentridges
} // end namespace _ApparentRidges
