// Generated by Haxe 4.1.3
#include <hxcpp.h>

#ifndef INCLUDED_95f339a1d026d52c
#define INCLUDED_95f339a1d026d52c
#include "hxMath.h"
#endif
#ifndef INCLUDED_apparentridges__ApparentRidges_Vec3_Impl_
#include <apparentridges/_ApparentRidges/Vec3_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_174__new,"apparentridges._ApparentRidges.Vec3_Impl_","_new",0x351336d5,"apparentridges._ApparentRidges.Vec3_Impl_._new","apparentridges/ApparentRidges.hx",174,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_180_get_x,"apparentridges._ApparentRidges.Vec3_Impl_","get_x",0xd109c95b,"apparentridges._ApparentRidges.Vec3_Impl_.get_x","apparentridges/ApparentRidges.hx",180,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_181_get_y,"apparentridges._ApparentRidges.Vec3_Impl_","get_y",0xd109c95c,"apparentridges._ApparentRidges.Vec3_Impl_.get_y","apparentridges/ApparentRidges.hx",181,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_182_get_z,"apparentridges._ApparentRidges.Vec3_Impl_","get_z",0xd109c95d,"apparentridges._ApparentRidges.Vec3_Impl_.get_z","apparentridges/ApparentRidges.hx",182,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_183_set_x,"apparentridges._ApparentRidges.Vec3_Impl_","set_x",0xb9d8bf67,"apparentridges._ApparentRidges.Vec3_Impl_.set_x","apparentridges/ApparentRidges.hx",183,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_184_set_y,"apparentridges._ApparentRidges.Vec3_Impl_","set_y",0xb9d8bf68,"apparentridges._ApparentRidges.Vec3_Impl_.set_y","apparentridges/ApparentRidges.hx",184,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_185_set_z,"apparentridges._ApparentRidges.Vec3_Impl_","set_z",0xb9d8bf69,"apparentridges._ApparentRidges.Vec3_Impl_.set_z","apparentridges/ApparentRidges.hx",185,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_188_copy,"apparentridges._ApparentRidges.Vec3_Impl_","copy",0x37b8dd29,"apparentridges._ApparentRidges.Vec3_Impl_.copy","apparentridges/ApparentRidges.hx",188,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_190_assign,"apparentridges._ApparentRidges.Vec3_Impl_","assign",0xc05caca3,"apparentridges._ApparentRidges.Vec3_Impl_.assign","apparentridges/ApparentRidges.hx",190,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_195_cross,"apparentridges._ApparentRidges.Vec3_Impl_","cross",0x8c03838c,"apparentridges._ApparentRidges.Vec3_Impl_.cross","apparentridges/ApparentRidges.hx",195,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_202_dot,"apparentridges._ApparentRidges.Vec3_Impl_","dot",0x1aa80b95,"apparentridges._ApparentRidges.Vec3_Impl_.dot","apparentridges/ApparentRidges.hx",202,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_205_dist2,"apparentridges._ApparentRidges.Vec3_Impl_","dist2",0x197a3618,"apparentridges._ApparentRidges.Vec3_Impl_.dist2","apparentridges/ApparentRidges.hx",205,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_208_dist,"apparentridges._ApparentRidges.Vec3_Impl_","dist",0x385d88da,"apparentridges._ApparentRidges.Vec3_Impl_.dist","apparentridges/ApparentRidges.hx",208,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_212_len,"apparentridges._ApparentRidges.Vec3_Impl_","len",0x1aae14e1,"apparentridges._ApparentRidges.Vec3_Impl_.len","apparentridges/ApparentRidges.hx",212,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_215_len2,"apparentridges._ApparentRidges.Vec3_Impl_","len2",0x3da43031,"apparentridges._ApparentRidges.Vec3_Impl_.len2","apparentridges/ApparentRidges.hx",215,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_218_normalize,"apparentridges._ApparentRidges.Vec3_Impl_","normalize",0xc97b5199,"apparentridges._ApparentRidges.Vec3_Impl_.normalize","apparentridges/ApparentRidges.hx",218,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_231_scale,"apparentridges._ApparentRidges.Vec3_Impl_","scale",0xb877f296,"apparentridges._ApparentRidges.Vec3_Impl_.scale","apparentridges/ApparentRidges.hx",231,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_239_get,"apparentridges._ApparentRidges.Vec3_Impl_","get",0x1aaa49a2,"apparentridges._ApparentRidges.Vec3_Impl_.get","apparentridges/ApparentRidges.hx",239,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_242_set,"apparentridges._ApparentRidges.Vec3_Impl_","set",0x1ab364ae,"apparentridges._ApparentRidges.Vec3_Impl_.set","apparentridges/ApparentRidges.hx",242,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_249_add,"apparentridges._ApparentRidges.Vec3_Impl_","add",0x1aa5bb2d,"apparentridges._ApparentRidges.Vec3_Impl_.add","apparentridges/ApparentRidges.hx",249,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_253_sub,"apparentridges._ApparentRidges.Vec3_Impl_","sub",0x1ab3728c,"apparentridges._ApparentRidges.Vec3_Impl_.sub","apparentridges/ApparentRidges.hx",253,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_257_mul,"apparentridges._ApparentRidges.Vec3_Impl_","mul",0x1aaee510,"apparentridges._ApparentRidges.Vec3_Impl_.mul","apparentridges/ApparentRidges.hx",257,0xfeacc84f)
HX_LOCAL_STACK_FRAME(_hx_pos_7690e17e5d2a44f3_261_mulf,"apparentridges._ApparentRidges.Vec3_Impl_","mulf",0x3e598956,"apparentridges._ApparentRidges.Vec3_Impl_.mulf","apparentridges/ApparentRidges.hx",261,0xfeacc84f)
namespace apparentridges{
namespace _ApparentRidges{

void Vec3_Impl__obj::__construct() { }

Dynamic Vec3_Impl__obj::__CreateEmpty() { return new Vec3_Impl__obj; }

void *Vec3_Impl__obj::_hx_vtable = 0;

Dynamic Vec3_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Vec3_Impl__obj > _hx_result = new Vec3_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Vec3_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x003208de;
}

::Array< Float > Vec3_Impl__obj::_new(Float _x,Float _y,Float _z){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_174__new)
HXLINE( 175)		::Array< Float > this1 = ::Array_obj< Float >::__new(3);
HXLINE( 174)		::Array< Float > this2 = this1;
HXLINE( 176)		this2->__unsafe_set(0,_x);
HXLINE( 177)		this2->__unsafe_set(1,_y);
HXLINE( 178)		this2->__unsafe_set(2,_z);
HXLINE( 174)		return this2;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Vec3_Impl__obj,_new,return )

Float Vec3_Impl__obj::get_x(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_180_get_x)
HXDLIN( 180)		return ( (Float)(_hx_array_unsafe_get(this1,0)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,get_x,return )

Float Vec3_Impl__obj::get_y(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_181_get_y)
HXDLIN( 181)		return ( (Float)(_hx_array_unsafe_get(this1,1)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,get_y,return )

Float Vec3_Impl__obj::get_z(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_182_get_z)
HXDLIN( 182)		return ( (Float)(_hx_array_unsafe_get(this1,2)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,get_z,return )

Float Vec3_Impl__obj::set_x(::Array< Float > this1,Float v){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_183_set_x)
HXDLIN( 183)		return ( (Float)(this1->__unsafe_set(0,v)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,set_x,return )

Float Vec3_Impl__obj::set_y(::Array< Float > this1,Float v){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_184_set_y)
HXDLIN( 184)		return ( (Float)(this1->__unsafe_set(1,v)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,set_y,return )

Float Vec3_Impl__obj::set_z(::Array< Float > this1,Float v){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_185_set_z)
HXDLIN( 185)		return ( (Float)(this1->__unsafe_set(2,v)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,set_z,return )

::Array< Float > Vec3_Impl__obj::copy(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_188_copy)
HXDLIN( 188)		Float _x = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 188)		Float _y = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 188)		Float _z = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 188)		::Array< Float > this2 = ::Array_obj< Float >::__new(3);
HXDLIN( 188)		::Array< Float > this3 = this2;
HXDLIN( 188)		this3->__unsafe_set(0,_x);
HXDLIN( 188)		this3->__unsafe_set(1,_y);
HXDLIN( 188)		this3->__unsafe_set(2,_z);
HXDLIN( 188)		return this3;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,copy,return )

void Vec3_Impl__obj::assign(::Array< Float > this1,::Array< Float > v){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_190_assign)
HXLINE( 191)		{
HXLINE( 191)			Float v1 = ( (Float)(_hx_array_unsafe_get(v,0)) );
HXDLIN( 191)			this1->__unsafe_set(0,v1);
            		}
HXDLIN( 191)		{
HXLINE( 191)			Float v2 = ( (Float)(_hx_array_unsafe_get(v,1)) );
HXDLIN( 191)			this1->__unsafe_set(1,v2);
            		}
HXDLIN( 191)		{
HXLINE( 191)			Float v3 = ( (Float)(_hx_array_unsafe_get(v,2)) );
HXDLIN( 191)			this1->__unsafe_set(2,v3);
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,assign,(void))

::Array< Float > Vec3_Impl__obj::cross(::Array< Float > v1,::Array< Float > v2){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_195_cross)
HXLINE( 196)		Float _x = ( (Float)(_hx_array_unsafe_get(v1,1)) );
HXDLIN( 196)		Float _x1 = (_x * ( (Float)(_hx_array_unsafe_get(v2,2)) ));
HXDLIN( 196)		Float _x2 = ( (Float)(_hx_array_unsafe_get(v1,2)) );
HXLINE( 195)		Float _x3 = (_x1 - (_x2 * ( (Float)(_hx_array_unsafe_get(v2,1)) )));
HXLINE( 197)		Float _y = ( (Float)(_hx_array_unsafe_get(v1,2)) );
HXDLIN( 197)		Float _y1 = (_y * ( (Float)(_hx_array_unsafe_get(v2,0)) ));
HXDLIN( 197)		Float _y2 = ( (Float)(_hx_array_unsafe_get(v1,0)) );
HXLINE( 195)		Float _y3 = (_y1 - (_y2 * ( (Float)(_hx_array_unsafe_get(v2,2)) )));
HXLINE( 198)		Float _z = ( (Float)(_hx_array_unsafe_get(v1,0)) );
HXDLIN( 198)		Float _z1 = (_z * ( (Float)(_hx_array_unsafe_get(v2,1)) ));
HXDLIN( 198)		Float _z2 = ( (Float)(_hx_array_unsafe_get(v1,1)) );
HXLINE( 195)		Float _z3 = (_z1 - (_z2 * ( (Float)(_hx_array_unsafe_get(v2,0)) )));
HXDLIN( 195)		::Array< Float > this1 = ::Array_obj< Float >::__new(3);
HXDLIN( 195)		::Array< Float > this2 = this1;
HXDLIN( 195)		this2->__unsafe_set(0,_x3);
HXDLIN( 195)		this2->__unsafe_set(1,_y3);
HXDLIN( 195)		this2->__unsafe_set(2,_z3);
HXDLIN( 195)		return this2;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,cross,return )

Float Vec3_Impl__obj::dot(::Array< Float > v1,::Array< Float > v2){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_202_dot)
HXDLIN( 202)		Float _hx_tmp = ( (Float)(_hx_array_unsafe_get(v1,0)) );
HXDLIN( 202)		Float _hx_tmp1 = (_hx_tmp * ( (Float)(_hx_array_unsafe_get(v2,0)) ));
HXDLIN( 202)		Float _hx_tmp2 = ( (Float)(_hx_array_unsafe_get(v1,1)) );
HXDLIN( 202)		Float _hx_tmp3 = (_hx_tmp1 + (_hx_tmp2 * ( (Float)(_hx_array_unsafe_get(v2,1)) )));
HXDLIN( 202)		Float _hx_tmp4 = ( (Float)(_hx_array_unsafe_get(v1,2)) );
HXDLIN( 202)		return (_hx_tmp3 + (_hx_tmp4 * ( (Float)(_hx_array_unsafe_get(v2,2)) )));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,dot,return )

Float Vec3_Impl__obj::dist2(::Array< Float > v1,::Array< Float > v2){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_205_dist2)
HXDLIN( 205)		Float x = ( (Float)(_hx_array_unsafe_get(v1,0)) );
HXDLIN( 205)		Float x1 = (x - ( (Float)(_hx_array_unsafe_get(v2,0)) ));
HXDLIN( 205)		Float x2 = ( (Float)(_hx_array_unsafe_get(v1,1)) );
HXDLIN( 205)		Float x3 = (x2 - ( (Float)(_hx_array_unsafe_get(v2,1)) ));
HXDLIN( 205)		Float x4 = ( (Float)(_hx_array_unsafe_get(v1,2)) );
HXDLIN( 205)		Float x5 = (x4 - ( (Float)(_hx_array_unsafe_get(v2,2)) ));
HXDLIN( 205)		return (((x1 * x1) + (x3 * x3)) + (x5 * x5));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,dist2,return )

Float Vec3_Impl__obj::dist(::Array< Float > v1,::Array< Float > v2){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_208_dist)
HXDLIN( 208)		Float x = ( (Float)(_hx_array_unsafe_get(v1,0)) );
HXDLIN( 208)		Float x1 = (x - ( (Float)(_hx_array_unsafe_get(v2,0)) ));
HXDLIN( 208)		Float x2 = ( (Float)(_hx_array_unsafe_get(v1,1)) );
HXDLIN( 208)		Float x3 = (x2 - ( (Float)(_hx_array_unsafe_get(v2,1)) ));
HXDLIN( 208)		Float x4 = ( (Float)(_hx_array_unsafe_get(v1,2)) );
HXDLIN( 208)		Float x5 = (x4 - ( (Float)(_hx_array_unsafe_get(v2,2)) ));
HXDLIN( 208)		return ::Math_obj::sqrt((((x1 * x1) + (x3 * x3)) + (x5 * x5)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,dist,return )

Float Vec3_Impl__obj::len(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_212_len)
HXDLIN( 212)		Float _hx_tmp = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 212)		Float _hx_tmp1 = (_hx_tmp * ( (Float)(_hx_array_unsafe_get(this1,0)) ));
HXDLIN( 212)		Float _hx_tmp2 = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 212)		Float _hx_tmp3 = (_hx_tmp1 + (_hx_tmp2 * ( (Float)(_hx_array_unsafe_get(this1,1)) )));
HXDLIN( 212)		Float _hx_tmp4 = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 212)		return ::Math_obj::sqrt((_hx_tmp3 + (_hx_tmp4 * ( (Float)(_hx_array_unsafe_get(this1,2)) ))));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,len,return )

Float Vec3_Impl__obj::len2(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_215_len2)
HXDLIN( 215)		Float _hx_tmp = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 215)		Float _hx_tmp1 = (_hx_tmp * ( (Float)(_hx_array_unsafe_get(this1,0)) ));
HXDLIN( 215)		Float _hx_tmp2 = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 215)		Float _hx_tmp3 = (_hx_tmp1 + (_hx_tmp2 * ( (Float)(_hx_array_unsafe_get(this1,1)) )));
HXDLIN( 215)		Float _hx_tmp4 = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 215)		return (_hx_tmp3 + (_hx_tmp4 * ( (Float)(_hx_array_unsafe_get(this1,2)) )));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,len2,return )

void Vec3_Impl__obj::normalize(::Array< Float > this1){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_218_normalize)
HXLINE( 219)		Float l = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 219)		Float l1 = (l * ( (Float)(_hx_array_unsafe_get(this1,0)) ));
HXDLIN( 219)		Float l2 = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 219)		Float l3 = (l1 + (l2 * ( (Float)(_hx_array_unsafe_get(this1,1)) )));
HXDLIN( 219)		Float l4 = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 219)		Float l5 = ::Math_obj::sqrt((l3 + (l4 * ( (Float)(_hx_array_unsafe_get(this1,2)) ))));
HXLINE( 220)		if ((l5 > 0)) {
HXLINE( 221)			l5 = (( (Float)(1) ) / l5);
HXLINE( 222)			{
HXLINE( 222)				::Array< Float > _g = this1;
HXDLIN( 222)				{
HXLINE( 222)					Float v = (( (Float)(_hx_array_unsafe_get(_g,0)) ) * l5);
HXDLIN( 222)					_g->__unsafe_set(0,v);
            				}
            			}
HXLINE( 223)			{
HXLINE( 223)				::Array< Float > _g1 = this1;
HXDLIN( 223)				{
HXLINE( 223)					Float v1 = (( (Float)(_hx_array_unsafe_get(_g1,1)) ) * l5);
HXDLIN( 223)					_g1->__unsafe_set(1,v1);
            				}
            			}
HXLINE( 224)			{
HXLINE( 224)				::Array< Float > _g2 = this1;
HXDLIN( 224)				{
HXLINE( 224)					Float v2 = (( (Float)(_hx_array_unsafe_get(_g2,2)) ) * l5);
HXDLIN( 224)					_g2->__unsafe_set(2,v2);
            				}
            			}
            		}
            		else {
HXLINE( 226)			this1->__unsafe_set(0,0);
HXLINE( 227)			this1->__unsafe_set(1,0);
HXLINE( 228)			this1->__unsafe_set(2,1);
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Vec3_Impl__obj,normalize,(void))

void Vec3_Impl__obj::scale(::Array< Float > this1,Float s){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_231_scale)
HXLINE( 232)		{
HXLINE( 232)			::Array< Float > _g = this1;
HXDLIN( 232)			{
HXLINE( 232)				Float v = (( (Float)(_hx_array_unsafe_get(_g,0)) ) * s);
HXDLIN( 232)				_g->__unsafe_set(0,v);
            			}
            		}
HXLINE( 233)		{
HXLINE( 233)			::Array< Float > _g1 = this1;
HXDLIN( 233)			{
HXLINE( 233)				Float v1 = (( (Float)(_hx_array_unsafe_get(_g1,1)) ) * s);
HXDLIN( 233)				_g1->__unsafe_set(1,v1);
            			}
            		}
HXLINE( 234)		{
HXLINE( 234)			::Array< Float > _g2 = this1;
HXDLIN( 234)			{
HXLINE( 234)				Float v2 = (( (Float)(_hx_array_unsafe_get(_g2,2)) ) * s);
HXDLIN( 234)				_g2->__unsafe_set(2,v2);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,scale,(void))

Float Vec3_Impl__obj::get(::Array< Float > this1,int i){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_239_get)
HXDLIN( 239)		return ( (Float)(_hx_array_unsafe_get(this1,i)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,get,return )

Float Vec3_Impl__obj::set(::Array< Float > this1,int i,Float v){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_242_set)
HXLINE( 243)		this1->__unsafe_set(i,v);
HXLINE( 244)		return v;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Vec3_Impl__obj,set,return )

::Array< Float > Vec3_Impl__obj::add(::Array< Float > this1,::Array< Float > rhs){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_249_add)
HXDLIN( 249)		Float _x = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 249)		Float _x1 = (_x + ( (Float)(_hx_array_unsafe_get(rhs,0)) ));
HXDLIN( 249)		Float _y = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 249)		Float _y1 = (_y + ( (Float)(_hx_array_unsafe_get(rhs,1)) ));
HXDLIN( 249)		Float _z = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 249)		Float _z1 = (_z + ( (Float)(_hx_array_unsafe_get(rhs,2)) ));
HXDLIN( 249)		::Array< Float > this2 = ::Array_obj< Float >::__new(3);
HXDLIN( 249)		::Array< Float > this3 = this2;
HXDLIN( 249)		this3->__unsafe_set(0,_x1);
HXDLIN( 249)		this3->__unsafe_set(1,_y1);
HXDLIN( 249)		this3->__unsafe_set(2,_z1);
HXDLIN( 249)		return this3;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,add,return )

::Array< Float > Vec3_Impl__obj::sub(::Array< Float > this1,::Array< Float > rhs){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_253_sub)
HXDLIN( 253)		Float _x = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 253)		Float _x1 = (_x - ( (Float)(_hx_array_unsafe_get(rhs,0)) ));
HXDLIN( 253)		Float _y = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 253)		Float _y1 = (_y - ( (Float)(_hx_array_unsafe_get(rhs,1)) ));
HXDLIN( 253)		Float _z = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 253)		Float _z1 = (_z - ( (Float)(_hx_array_unsafe_get(rhs,2)) ));
HXDLIN( 253)		::Array< Float > this2 = ::Array_obj< Float >::__new(3);
HXDLIN( 253)		::Array< Float > this3 = this2;
HXDLIN( 253)		this3->__unsafe_set(0,_x1);
HXDLIN( 253)		this3->__unsafe_set(1,_y1);
HXDLIN( 253)		this3->__unsafe_set(2,_z1);
HXDLIN( 253)		return this3;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,sub,return )

::Array< Float > Vec3_Impl__obj::mul(::Array< Float > this1,::Array< Float > rhs){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_257_mul)
HXDLIN( 257)		Float _x = ( (Float)(_hx_array_unsafe_get(this1,0)) );
HXDLIN( 257)		Float _x1 = (_x * ( (Float)(_hx_array_unsafe_get(rhs,0)) ));
HXDLIN( 257)		Float _y = ( (Float)(_hx_array_unsafe_get(this1,1)) );
HXDLIN( 257)		Float _y1 = (_y * ( (Float)(_hx_array_unsafe_get(rhs,1)) ));
HXDLIN( 257)		Float _z = ( (Float)(_hx_array_unsafe_get(this1,2)) );
HXDLIN( 257)		Float _z1 = (_z * ( (Float)(_hx_array_unsafe_get(rhs,2)) ));
HXDLIN( 257)		::Array< Float > this2 = ::Array_obj< Float >::__new(3);
HXDLIN( 257)		::Array< Float > this3 = this2;
HXDLIN( 257)		this3->__unsafe_set(0,_x1);
HXDLIN( 257)		this3->__unsafe_set(1,_y1);
HXDLIN( 257)		this3->__unsafe_set(2,_z1);
HXDLIN( 257)		return this3;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,mul,return )

::Array< Float > Vec3_Impl__obj::mulf(::Array< Float > this1,Float rhs){
            	HX_STACKFRAME(&_hx_pos_7690e17e5d2a44f3_261_mulf)
HXDLIN( 261)		Float _x = (( (Float)(_hx_array_unsafe_get(this1,0)) ) * rhs);
HXDLIN( 261)		Float _y = (( (Float)(_hx_array_unsafe_get(this1,1)) ) * rhs);
HXDLIN( 261)		Float _z = (( (Float)(_hx_array_unsafe_get(this1,2)) ) * rhs);
HXDLIN( 261)		::Array< Float > this2 = ::Array_obj< Float >::__new(3);
HXDLIN( 261)		::Array< Float > this3 = this2;
HXDLIN( 261)		this3->__unsafe_set(0,_x);
HXDLIN( 261)		this3->__unsafe_set(1,_y);
HXDLIN( 261)		this3->__unsafe_set(2,_z);
HXDLIN( 261)		return this3;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Vec3_Impl__obj,mulf,return )


Vec3_Impl__obj::Vec3_Impl__obj()
{
}

bool Vec3_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"dot") ) { outValue = dot_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"len") ) { outValue = len_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set") ) { outValue = set_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"add") ) { outValue = add_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"sub") ) { outValue = sub_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"mul") ) { outValue = mul_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"copy") ) { outValue = copy_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"dist") ) { outValue = dist_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"len2") ) { outValue = len2_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"mulf") ) { outValue = mulf_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"get_x") ) { outValue = get_x_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_y") ) { outValue = get_y_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_z") ) { outValue = get_z_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_x") ) { outValue = set_x_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_y") ) { outValue = set_y_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_z") ) { outValue = set_z_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"cross") ) { outValue = cross_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"dist2") ) { outValue = dist2_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"scale") ) { outValue = scale_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"assign") ) { outValue = assign_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"normalize") ) { outValue = normalize_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Vec3_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Vec3_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class Vec3_Impl__obj::__mClass;

static ::String Vec3_Impl__obj_sStaticFields[] = {
	HX_("_new",61,15,1f,3f),
	HX_("get_x",4f,a5,60,91),
	HX_("get_y",50,a5,60,91),
	HX_("get_z",51,a5,60,91),
	HX_("set_x",5b,9b,2f,7a),
	HX_("set_y",5c,9b,2f,7a),
	HX_("set_z",5d,9b,2f,7a),
	HX_("copy",b5,bb,c4,41),
	HX_("assign",2f,46,06,4c),
	HX_("cross",80,5f,5a,4c),
	HX_("dot",89,42,4c,00),
	HX_("dist2",0c,12,d1,d9),
	HX_("dist",66,67,69,42),
	HX_("len",d5,4b,52,00),
	HX_("len2",bd,0e,b0,47),
	HX_("normalize",8d,37,a1,ab),
	HX_("scale",8a,ce,ce,78),
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("add",21,f2,49,00),
	HX_("sub",80,a9,57,00),
	HX_("mul",04,1c,53,00),
	HX_("mulf",e2,67,65,48),
	::String(null())
};

void Vec3_Impl__obj::__register()
{
	Vec3_Impl__obj _hx_dummy;
	Vec3_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("apparentridges._ApparentRidges.Vec3_Impl_",7a,b3,bb,09);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Vec3_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Vec3_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Vec3_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Vec3_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Vec3_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace apparentridges
} // end namespace _ApparentRidges
