// Generated by Haxe 4.1.3
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_sys_io_FileOutput
#include <sys/io/FileOutput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_apparentridges_SVGWriter
#include <apparentridges/SVGWriter.h>
#endif
#ifndef INCLUDED_apparentridges_PixelMap
#include <apparentridges/PixelMap.h>
#endif
#ifndef INCLUDED_apparentridges_Render
#include <apparentridges/Render.h>
#endif
#ifndef INCLUDED_apparentridges__ApparentRidges_Polyline_Impl_
#include <apparentridges/_ApparentRidges/Polyline_Impl_.h>
#endif
#ifndef INCLUDED_apparentridges_Line
#include <apparentridges/Line.h>
#endif
#ifndef INCLUDED_apparentridges_OBJParser
#include <apparentridges/OBJParser.h>
#endif
#ifndef INCLUDED_apparentridges_BVHPartition
#include <apparentridges/BVHPartition.h>
#endif
#ifndef INCLUDED_apparentridges_BVHBucket
#include <apparentridges/BVHBucket.h>
#endif
#ifndef INCLUDED_apparentridges_BVHTree
#include <apparentridges/BVHTree.h>
#endif
#ifndef INCLUDED_apparentridges_BVHNode
#include <apparentridges/BVHNode.h>
#endif
#ifndef INCLUDED_apparentridges_BBox
#include <apparentridges/BBox.h>
#endif
#ifndef INCLUDED_apparentridges_RayHit
#include <apparentridges/RayHit.h>
#endif
#ifndef INCLUDED_apparentridges_Ray
#include <apparentridges/Ray.h>
#endif
#ifndef INCLUDED_apparentridges_Mesh
#include <apparentridges/Mesh.h>
#endif
#ifndef INCLUDED_apparentridges_BSphere
#include <apparentridges/BSphere.h>
#endif
#ifndef INCLUDED_apparentridges_Ridge
#include <apparentridges/Ridge.h>
#endif
#ifndef INCLUDED_apparentridges__ApparentRidges_Face_Impl_
#include <apparentridges/_ApparentRidges/Face_Impl_.h>
#endif
#ifndef INCLUDED_apparentridges__ApparentRidges_Vec3_Impl_
#include <apparentridges/_ApparentRidges/Vec3_Impl_.h>
#endif
#ifndef INCLUDED_apparentridges_Util
#include <apparentridges/Util.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::haxe::Log_obj::__register();
::sys::io::FileOutput_obj::__register();
::sys::io::File_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::apparentridges::SVGWriter_obj::__register();
::apparentridges::PixelMap_obj::__register();
::apparentridges::Render_obj::__register();
::apparentridges::_ApparentRidges::Polyline_Impl__obj::__register();
::apparentridges::Line_obj::__register();
::apparentridges::OBJParser_obj::__register();
::apparentridges::BVHPartition_obj::__register();
::apparentridges::BVHBucket_obj::__register();
::apparentridges::BVHTree_obj::__register();
::apparentridges::BVHNode_obj::__register();
::apparentridges::BBox_obj::__register();
::apparentridges::RayHit_obj::__register();
::apparentridges::Ray_obj::__register();
::apparentridges::Mesh_obj::__register();
::apparentridges::BSphere_obj::__register();
::apparentridges::Ridge_obj::__register();
::apparentridges::_ApparentRidges::Face_Impl__obj::__register();
::apparentridges::_ApparentRidges::Vec3_Impl__obj::__register();
::apparentridges::Util_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::haxe::Log_obj::__boot();
}

