// Generated by HLC 4.1.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <apparentridges/BBox.h>
#include <_std/Math.h>
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
extern hl_type t$_dyn;
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
extern $Math g$_Math;
double Math_min(double,double);
double Math_max(double,double);

void apparentridges_BBox_new(apparentridges__BBox r0) {
	$Math r9;
	hl__types__ArrayBytes_Float r1, r8;
	double r6;
	vdynamic *r5;
	int r3, r7;
	vbyte *r2;
	r3 = 0;
	r2 = hl_alloc_bytes(r3);
	r3 = 0;
	r3 = 0;
	r1 = hl_types_ArrayBase_allocF64(r2,r3);
	if( r1 == NULL ) hl_null_access();
	r3 = 2;
	r5 = NULL;
	r6 = (double)hl_dyn_castd(&r5,&t$_dyn);
	r7 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_12;
	hl_types_ArrayBytes_Float___expand(r1,r3);
	label$7c2e5de_1_12:
	r2 = r1->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 0;
	r9 = ($Math)g$_Math;
	r6 = r9->POSITIVE_INFINITY;
	r7 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_22;
	hl_types_ArrayBytes_Float___expand(r1,r3);
	label$7c2e5de_1_22:
	r2 = r1->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 1;
	r9 = ($Math)g$_Math;
	r6 = r9->POSITIVE_INFINITY;
	r7 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_32;
	hl_types_ArrayBytes_Float___expand(r1,r3);
	label$7c2e5de_1_32:
	r2 = r1->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 2;
	r9 = ($Math)g$_Math;
	r6 = r9->POSITIVE_INFINITY;
	r7 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_42;
	hl_types_ArrayBytes_Float___expand(r1,r3);
	label$7c2e5de_1_42:
	r2 = r1->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r0->min = r1;
	r3 = 0;
	r2 = hl_alloc_bytes(r3);
	r3 = 0;
	r3 = 0;
	r8 = hl_types_ArrayBase_allocF64(r2,r3);
	if( r8 == NULL ) hl_null_access();
	r3 = 2;
	r5 = NULL;
	r6 = (double)hl_dyn_castd(&r5,&t$_dyn);
	r7 = r8->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_59;
	hl_types_ArrayBytes_Float___expand(r8,r3);
	label$7c2e5de_1_59:
	r2 = r8->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 0;
	r9 = ($Math)g$_Math;
	r6 = r9->NEGATIVE_INFINITY;
	r7 = r8->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_69;
	hl_types_ArrayBytes_Float___expand(r8,r3);
	label$7c2e5de_1_69:
	r2 = r8->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 1;
	r9 = ($Math)g$_Math;
	r6 = r9->NEGATIVE_INFINITY;
	r7 = r8->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_79;
	hl_types_ArrayBytes_Float___expand(r8,r3);
	label$7c2e5de_1_79:
	r2 = r8->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r3 = 2;
	r9 = ($Math)g$_Math;
	r6 = r9->NEGATIVE_INFINITY;
	r7 = r8->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$7c2e5de_1_89;
	hl_types_ArrayBytes_Float___expand(r8,r3);
	label$7c2e5de_1_89:
	r2 = r8->bytes;
	r7 = 3;
	r7 = r3 << r7;
	*(double*)(r2 + r7) = r6;
	r0->max = r8;
	return;
}

hl__types__ArrayBytes_Float apparentridges_BBox_centroid(apparentridges__BBox r0) {
	hl__types__ArrayBytes_Float r1, r3, r4, r10;
	double r8, r12;
	vdynamic *r7;
	int r6, r9, r11;
	vbyte *r5;
	r1 = r0->min;
	r3 = r0->max;
	r6 = 0;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	r6 = 0;
	r4 = hl_types_ArrayBase_allocF64(r5,r6);
	if( r4 == NULL ) hl_null_access();
	r6 = 2;
	r7 = NULL;
	r8 = (double)hl_dyn_castd(&r7,&t$_dyn);
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_14;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_2_14:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 0;
	if( r1 == NULL ) hl_null_access();
	r9 = 0;
	r11 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_25;
	r8 = 0.;
	goto label$7c2e5de_2_29;
	label$7c2e5de_2_25:
	r5 = r1->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_29:
	if( r3 == NULL ) hl_null_access();
	r9 = 0;
	r11 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_35;
	r12 = 0.;
	goto label$7c2e5de_2_39;
	label$7c2e5de_2_35:
	r5 = r3->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r12 = *(double*)(r5 + r11);
	label$7c2e5de_2_39:
	r8 = r8 + r12;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_43;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_2_43:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 1;
	r9 = 1;
	r11 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_53;
	r8 = 0.;
	goto label$7c2e5de_2_57;
	label$7c2e5de_2_53:
	r5 = r1->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_57:
	r9 = 1;
	r11 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_62;
	r12 = 0.;
	goto label$7c2e5de_2_66;
	label$7c2e5de_2_62:
	r5 = r3->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r12 = *(double*)(r5 + r11);
	label$7c2e5de_2_66:
	r8 = r8 + r12;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_70;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_2_70:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 2;
	r9 = 2;
	r11 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_80;
	r8 = 0.;
	goto label$7c2e5de_2_84;
	label$7c2e5de_2_80:
	r5 = r1->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_84:
	r9 = 2;
	r11 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_89;
	r12 = 0.;
	goto label$7c2e5de_2_93;
	label$7c2e5de_2_89:
	r5 = r3->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r12 = *(double*)(r5 + r11);
	label$7c2e5de_2_93:
	r8 = r8 + r12;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_97;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_2_97:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 0;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	r6 = 0;
	r10 = hl_types_ArrayBase_allocF64(r5,r6);
	if( r10 == NULL ) hl_null_access();
	r6 = 2;
	r7 = NULL;
	r8 = (double)hl_dyn_castd(&r7,&t$_dyn);
	r9 = r10->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_113;
	hl_types_ArrayBytes_Float___expand(r10,r6);
	label$7c2e5de_2_113:
	r5 = r10->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 0;
	r9 = 0;
	r11 = r4->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_123;
	r8 = 0.;
	goto label$7c2e5de_2_127;
	label$7c2e5de_2_123:
	r5 = r4->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_127:
	r12 = 0.5;
	r8 = r8 * r12;
	r9 = r10->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_132;
	hl_types_ArrayBytes_Float___expand(r10,r6);
	label$7c2e5de_2_132:
	r5 = r10->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 1;
	r9 = 1;
	r11 = r4->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_142;
	r8 = 0.;
	goto label$7c2e5de_2_146;
	label$7c2e5de_2_142:
	r5 = r4->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_146:
	r12 = 0.5;
	r8 = r8 * r12;
	r9 = r10->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_151;
	hl_types_ArrayBytes_Float___expand(r10,r6);
	label$7c2e5de_2_151:
	r5 = r10->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 2;
	r9 = 2;
	r11 = r4->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$7c2e5de_2_161;
	r8 = 0.;
	goto label$7c2e5de_2_165;
	label$7c2e5de_2_161:
	r5 = r4->bytes;
	r11 = 3;
	r11 = r9 << r11;
	r8 = *(double*)(r5 + r11);
	label$7c2e5de_2_165:
	r12 = 0.5;
	r8 = r8 * r12;
	r9 = r10->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_2_170;
	hl_types_ArrayBytes_Float___expand(r10,r6);
	label$7c2e5de_2_170:
	r5 = r10->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	return r10;
}

void apparentridges_BBox_add(apparentridges__BBox r0,hl__types__ArrayBytes_Float r1) {
	hl__types__ArrayBytes_Float r2, r5;
	double r4, r9;
	vbyte *r8;
	int r3, r6, r7;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_10;
	r4 = 0.;
	goto label$7c2e5de_3_14;
	label$7c2e5de_3_10:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_14:
	if( r1 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_20;
	r9 = 0.;
	goto label$7c2e5de_3_24;
	label$7c2e5de_3_20:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_24:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_28;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_28:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_42;
	r4 = 0.;
	goto label$7c2e5de_3_46;
	label$7c2e5de_3_42:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_46:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_51;
	r9 = 0.;
	goto label$7c2e5de_3_55;
	label$7c2e5de_3_51:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_55:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_59;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_59:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_73;
	r4 = 0.;
	goto label$7c2e5de_3_77;
	label$7c2e5de_3_73:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_77:
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_82;
	r9 = 0.;
	goto label$7c2e5de_3_86;
	label$7c2e5de_3_82:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_86:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_90;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_90:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_104;
	r4 = 0.;
	goto label$7c2e5de_3_108;
	label$7c2e5de_3_104:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_108:
	r6 = 0;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_113;
	r9 = 0.;
	goto label$7c2e5de_3_117;
	label$7c2e5de_3_113:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_117:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_121;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_121:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_135;
	r4 = 0.;
	goto label$7c2e5de_3_139;
	label$7c2e5de_3_135:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_139:
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_144;
	r9 = 0.;
	goto label$7c2e5de_3_148;
	label$7c2e5de_3_144:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_148:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_152;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_152:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_166;
	r4 = 0.;
	goto label$7c2e5de_3_170;
	label$7c2e5de_3_166:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_3_170:
	r6 = 2;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_3_175;
	r9 = 0.;
	goto label$7c2e5de_3_179;
	label$7c2e5de_3_175:
	r8 = r1->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_3_179:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_3_183;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_3_183:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	return;
}

void apparentridges_BBox_merge(apparentridges__BBox r0,apparentridges__BBox r1) {
	hl__types__ArrayBytes_Float r2, r5;
	double r4, r9;
	vbyte *r8;
	int r3, r6, r7;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_10;
	r4 = 0.;
	goto label$7c2e5de_4_14;
	label$7c2e5de_4_10:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_14:
	if( r1 == NULL ) hl_null_access();
	r5 = r1->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_22;
	r9 = 0.;
	goto label$7c2e5de_4_26;
	label$7c2e5de_4_22:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_26:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_30;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_30:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_44;
	r4 = 0.;
	goto label$7c2e5de_4_48;
	label$7c2e5de_4_44:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_48:
	r5 = r1->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_55;
	r9 = 0.;
	goto label$7c2e5de_4_59;
	label$7c2e5de_4_55:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_59:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_63;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_63:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->min;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r5 = r0->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_77;
	r4 = 0.;
	goto label$7c2e5de_4_81;
	label$7c2e5de_4_77:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_81:
	r5 = r1->min;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_88;
	r9 = 0.;
	goto label$7c2e5de_4_92;
	label$7c2e5de_4_88:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_92:
	r4 = Math_min(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_96;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_96:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_110;
	r4 = 0.;
	goto label$7c2e5de_4_114;
	label$7c2e5de_4_110:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_114:
	r5 = r1->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_121;
	r9 = 0.;
	goto label$7c2e5de_4_125;
	label$7c2e5de_4_121:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_125:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_129;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_129:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_143;
	r4 = 0.;
	goto label$7c2e5de_4_147;
	label$7c2e5de_4_143:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_147:
	r5 = r1->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 1;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_154;
	r9 = 0.;
	goto label$7c2e5de_4_158;
	label$7c2e5de_4_154:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_158:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_162;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_162:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	r2 = r0->max;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r5 = r0->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_176;
	r4 = 0.;
	goto label$7c2e5de_4_180;
	label$7c2e5de_4_176:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r4 = *(double*)(r8 + r7);
	label$7c2e5de_4_180:
	r5 = r1->max;
	if( r5 == NULL ) hl_null_access();
	r6 = 2;
	r7 = r5->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$7c2e5de_4_187;
	r9 = 0.;
	goto label$7c2e5de_4_191;
	label$7c2e5de_4_187:
	r8 = r5->bytes;
	r7 = 3;
	r7 = r6 << r7;
	r9 = *(double*)(r8 + r7);
	label$7c2e5de_4_191:
	r4 = Math_max(r4,r9);
	r6 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r6) ) goto label$7c2e5de_4_195;
	hl_types_ArrayBytes_Float___expand(r2,r3);
	label$7c2e5de_4_195:
	r8 = r2->bytes;
	r6 = 3;
	r6 = r3 << r6;
	*(double*)(r8 + r6) = r4;
	return;
}

double apparentridges_BBox_surfaceArea(apparentridges__BBox r0) {
	hl__types__ArrayBytes_Float r1, r3, r4;
	double r8, r11, r12, r13, r14, r15;
	vdynamic *r7;
	int r6, r9, r10;
	vbyte *r5;
	r1 = r0->max;
	r3 = r0->min;
	r6 = 0;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	r6 = 0;
	r4 = hl_types_ArrayBase_allocF64(r5,r6);
	if( r4 == NULL ) hl_null_access();
	r6 = 2;
	r7 = NULL;
	r8 = (double)hl_dyn_castd(&r7,&t$_dyn);
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_14;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_5_14:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 0;
	if( r1 == NULL ) hl_null_access();
	r9 = 0;
	r10 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_25;
	r8 = 0.;
	goto label$7c2e5de_5_29;
	label$7c2e5de_5_25:
	r5 = r1->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r8 = *(double*)(r5 + r10);
	label$7c2e5de_5_29:
	if( r3 == NULL ) hl_null_access();
	r9 = 0;
	r10 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_35;
	r11 = 0.;
	goto label$7c2e5de_5_39;
	label$7c2e5de_5_35:
	r5 = r3->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r11 = *(double*)(r5 + r10);
	label$7c2e5de_5_39:
	r8 = r8 - r11;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_43;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_5_43:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 1;
	r9 = 1;
	r10 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_53;
	r8 = 0.;
	goto label$7c2e5de_5_57;
	label$7c2e5de_5_53:
	r5 = r1->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r8 = *(double*)(r5 + r10);
	label$7c2e5de_5_57:
	r9 = 1;
	r10 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_62;
	r11 = 0.;
	goto label$7c2e5de_5_66;
	label$7c2e5de_5_62:
	r5 = r3->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r11 = *(double*)(r5 + r10);
	label$7c2e5de_5_66:
	r8 = r8 - r11;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_70;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_5_70:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 2;
	r9 = 2;
	r10 = r1->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_80;
	r8 = 0.;
	goto label$7c2e5de_5_84;
	label$7c2e5de_5_80:
	r5 = r1->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r8 = *(double*)(r5 + r10);
	label$7c2e5de_5_84:
	r9 = 2;
	r10 = r3->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$7c2e5de_5_89;
	r11 = 0.;
	goto label$7c2e5de_5_93;
	label$7c2e5de_5_89:
	r5 = r3->bytes;
	r10 = 3;
	r10 = r9 << r10;
	r11 = *(double*)(r5 + r10);
	label$7c2e5de_5_93:
	r8 = r8 - r11;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_97;
	hl_types_ArrayBytes_Float___expand(r4,r6);
	label$7c2e5de_5_97:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	*(double*)(r5 + r9) = r8;
	r6 = 0;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_106;
	r8 = 0.;
	goto label$7c2e5de_5_110;
	label$7c2e5de_5_106:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	r8 = *(double*)(r5 + r9);
	label$7c2e5de_5_110:
	r11 = 0.;
	r8 = Math_max(r8,r11);
	r6 = 1;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_117;
	r11 = 0.;
	goto label$7c2e5de_5_121;
	label$7c2e5de_5_117:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	r11 = *(double*)(r5 + r9);
	label$7c2e5de_5_121:
	r12 = 0.;
	r11 = Math_max(r11,r12);
	r6 = 2;
	r9 = r4->length;
	if( ((unsigned)r6) < ((unsigned)r9) ) goto label$7c2e5de_5_128;
	r12 = 0.;
	goto label$7c2e5de_5_132;
	label$7c2e5de_5_128:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r6 << r9;
	r12 = *(double*)(r5 + r9);
	label$7c2e5de_5_132:
	r13 = 0.;
	r12 = Math_max(r12,r13);
	r13 = 2.;
	r14 = r8 * r12;
	r15 = r8 * r11;
	r14 = r14 + r15;
	r15 = r11 * r12;
	r14 = r14 + r15;
	r13 = r13 * r14;
	return r13;
}

