// Generated by HLC 4.1.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <apparentridges/Line.h>

void apparentridges_Line_setOpacity(apparentridges__Line r0,double r1,double r2) {
	r0->opacity1 = r1;
	r0->opacity2 = r2;
	return;
}

void apparentridges_Line_flip(apparentridges__Line r0) {
	double r1, r3;
	r1 = r0->x1;
	r3 = r0->x2;
	r0->x1 = r3;
	r0->x2 = r1;
	r3 = r0->y1;
	r1 = r3;
	r3 = r0->y2;
	r0->y1 = r3;
	r0->y2 = r1;
	r3 = r0->opacity1;
	r1 = r3;
	r3 = r0->opacity2;
	r0->opacity1 = r3;
	r0->opacity2 = r1;
	return;
}

void apparentridges_Line_new(apparentridges__Line r0,double r1,double r2,double r3,double r4) {
	double r5;
	r5 = 1.;
	r0->opacity2 = r5;
	r5 = 1.;
	r0->opacity1 = r5;
	r0->x1 = r1;
	r0->y1 = r2;
	r0->x2 = r3;
	r0->y2 = r4;
	return;
}

