// Generated by HLC 4.1.3 (HL v4)
#ifndef INC_apparentridges__PixelMap
#define INC_apparentridges__PixelMap
typedef struct _apparentridges__$PixelMap *apparentridges__$PixelMap;
typedef struct _apparentridges__PixelMap *apparentridges__PixelMap;
#include <apparentridges/Render.h>
#include <hl/types/ArrayBytes_Float.h>
#include <apparentridges/PixelMap.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <apparentridges/RayHit.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	apparentridges__Render p0;
	int p1;
	hl__types__ArrayBytes_Float p2;
	hl__types__ArrayBytes_Float p3;
	hl__types__ArrayBytes_Float p4;
} Enumt$ctx_d7acd6f;
typedef struct {
	HL__ENUM_CONSTRUCT__
	apparentridges__Render p0;
	hl__types__ArrayBytes_Float p1;
	hl__types__ArrayBytes_Float p2;
	hl__types__ArrayBytes_Float p3;
	hl__types__ArrayBytes_Float p4;
} Enumt$ctx_296a9bc;
typedef struct {
	HL__ENUM_CONSTRUCT__
	apparentridges__Render p0;
	hl__types__ArrayBytes_Float p1;
} Enumt$ctx_8719ba8;
typedef struct {
	HL__ENUM_CONSTRUCT__
	apparentridges__Render p0;
	hl__types__ArrayBytes_Float p1;
	hl__types__ArrayBytes_Float p2;
	hl__types__ArrayBytes_Float p3;
} Enumt$ctx_507de25;
struct _apparentridges__$PixelMap {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* raycast;
	vclosure* depth;
	vclosure* normal;
	vclosure* curvature;
	vclosure* lambertian;
	vclosure* ambientOcclusion;
	vclosure* toPPMString;
};
struct _apparentridges__PixelMap {
	hl_type *$type;
};
#endif

