// Generated by HLC 4.1.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <apparentridges/RayHit.h>

void apparentridges_RayHit_new(apparentridges__RayHit r0,double r1) {
	r0->_t = r1;
	return;
}

