// Generated by HLC 4.1.3 (HL v4)
#ifndef INC_hl__ctx__774e9
#define INC_hl__ctx__774e9
#include <apparentridges/BVHTree.h>
#include <hl/types/ArrayObj.h>
#include <hl/types/ArrayBytes_Float.h>
#include <hl/ctx/774e9.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	apparentridges__BVHTree p0;
	hl__types__ArrayObj p1;
	hl__types__ArrayBytes_Float p2;
	hl__types__ArrayBytes_Float p3;
	double p4;
	double p5;
} Enumt$ctx_d7774e9;
#endif

